import { AlertOctagon, AlertTriangle, ShieldAlert, Cpu, CheckCircle } from "lucide-react";

export const alertsData = [
  {
    id: "th-1",
    title: "Critical Fraud Alert",
    subtitle: "Luna Bloom • ₦450,000",
    description: "Multiple high-value transactions from new device (SIM swap suspected)",
    severity: "Critical",
    status: "New",
    isNew: true,
    type: "Transaction",
    time: "08:42 AM",
    icon: AlertOctagon,
    color: "#ff1744",
    rule: "Velocity Check",
    transaction: {
      customer: "Luna Bloom",
      amount: "₦450,000",
      merchant: "Krusty Mart",
      location: "Lagos, NG",
      risk: 92,
    },
  },
  {
    id: "th-2",
    title: "High Risk Transaction",
    subtitle: "Patty Star • ₦450,000",
    description: "Unusual location (foreign country) + high amount",
    severity: "High",
    status: "New",
    isNew: true,
    type: "Transaction",
    time: "07:15 AM",
    icon: AlertTriangle,
    color: "#ff007f",
    rule: "High Risk Location",
    transaction: {
      customer: "Patty Star",
      amount: "₦450,000",
      merchant: "JellyPay",
      location: "Starfish Shore",
      risk: 82,
    },
  },
  {
    id: "th-3",
    title: "Suspicious Activity",
    subtitle: "JellyPay • ₦230,000",
    description: "Velocity check triggered (8 txns in 5 min)",
    severity: "Warning",
    status: "New",
    isNew: true,
    type: "Behavior",
    time: "06:27 AM",
    icon: ShieldAlert,
    color: "#ffb300",
    rule: "Velocity Check",
    transaction: {
      customer: "Gary Shell",
      amount: "₦230,000",
      merchant: "Bikini Transfer",
      location: "Bubble Bay",
      risk: 74,
    },
  },
  {
    id: "th-4",
    title: "Device Anomaly",
    subtitle: "Fin Harbor • iPhone 14",
    description: "New device fingerprint detected",
    severity: "Warning",
    status: "New",
    isNew: true,
    type: "Device",
    time: "04:12 AM",
    icon: Cpu,
    color: "#ffb300",
    rule: "Device Mismatch",
  },
  {
    id: "th-5",
    title: "Velocity Rule Triggered",
    subtitle: "Coral Finch • Multiple txns",
    description: "Exceeded total daily limits in short window",
    severity: "Info",
    status: "In Review",
    isNew: false,
    type: "Behavior",
    time: "02:37 AM",
    icon: ShieldAlert,
    color: "#00e5ff",
    rule: "Velocity Limit",
  },
  {
    id: "th-6",
    title: "False Positive Resolved",
    subtitle: "Maple Muffin • ₦120,000",
    description: "Previously flagged transaction reviewed and cleared",
    severity: "Info",
    status: "Resolved",
    isNew: false,
    type: "Resolution",
    time: "Yesterday, 11:24 PM",
    icon: CheckCircle,
    color: "#10b981",
    rule: "Amount Threshold",
  },
];